language: node_js
node_js: 
  - "stable"

services:
  - mongodb

script:
  - npm run seed-user #This call the script inside the packaje.json. "node seed/user-seeder.js"
  - npm run seed-landingpage

cache:
  directories:
    - "node_modules"
