language: node_js
node_js:
- stable
services:
- mongodb
before_script:
- sleep 15
before_install:
- openssl aes-256-cbc -K $encrypted_d9505987b937_key -iv $encrypted_d9505987b937_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mkdir -p ./server/config
- mv ./service-account.json /server/config/service-account.json
script:
- npm run test
cache:
  directories:
  - node_modules
